pm_api_url      = "https://192.168.127.134:8006/api2/json"
pm_user         = "root"
pm_password     = "rootroot"
clone_template  = "tmpsouha"
target_node     = "node"
target_storage  = "node"
bridge          = "your-bridge-name"
disk_size       = "1G"
os_type         = "l26"  # Adjust this value if needed
